CREATE TABLE bookmarks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    description TEXT,
    rating INTEGER NOT NULL DEFAULT 0
);


INSERT INTO bookmarks
    (id, title, url, rating, description)
VALUES
    (1, 'Thinkful', 'https://www.thinkful.com', '5', 'Think outside the classroom'),
    (2, 'Google', 'https://www.google.com', '4', 'Where we find everything else'),
    (3, 'MDN', 'https://developer.mozilla.org', '5', 'The only place to find web documentation');